/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CalcJNI */

#ifndef _Included_CalcJNI
#define _Included_CalcJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CalcJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_CalcJNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     CalcJNI
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_CalcJNI_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     CalcJNI
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_CalcJNI_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     CalcJNI
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_CalcJNI_div
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
